In [1]:
import matplotlib.pyplot as py
import numpy as np
import math
from pylab import *
from ddeint import ddeint
import random

In [2]:
#change to array everthing in the code
#mark each portion of the code with specific code word
#

In [3]:
# parameters
def param():
    N = 10 # no. of particles
    L = 20 #length
    r = 10 # radius
    M = 4 #threshold particles
    eps = 0.001 #repulsion
    crep = 2.5 #repulsion coefficient
    cali = 3 #alignment coefficient
    catt =  0.01 #attraction coefficient
    return N,L,r,M,eps,crep, cali, catt

In [4]:
#x = [random.randrange(10, 300, 1)*0.1 for i in range(N)]
#y = [random.randrange(10, 300, 1)*0.1 for i in range(N)]

#print(x,y)

In [5]:
N,L,r,M,eps,crep, cali, catt = param()
#def position():
    # bird positions
x = np.random.rand(N, 1) * L
y = np.random.rand(N, 1) * L

#loc = [x.tolist(),y.tolist()]
loc = np.array([x,y])



#print(loc[0])
#print(type(x))


# velocity positions , velcity is suppose to null
v= [np.zeros(N),np.zeros(N)]
#v = np.array([vx,vy])
#v = (x, y)
#print(v)  


In [6]:
# distance matrix
#distance calculation function

def calc(x1, y1, x2, y2 ):
    po = round(math.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2), 2)
    return po
    
def distance(x,y):
    N,L,r,M,eps,crep, cali, catt = param()
    
    dis_mat = [[] for x in range(N)]
    ed = [[] for x in range(N)]
    #dismat matrix update
    for j in range(N):
        for i in range(N):
            dis_mat[j].append(calc(x[i], y[i], x[j], y[j]))

    dis_mat = np.array(dis_mat)

    print((dis_mat))
    
    #copy of distance matrix
    s_m = dis_mat
    
    #sorting and indexing

    s = [[] for x in range(N)]
    for i in range(0,N):
        s[i] = np.argsort(dis_mat[i]) #indexing
    
    for i in range(0,N):
        dis_mat[i].sort() #sorting
    
    #less than r only
    ed = (dis_mat < r).astype(int)
    #print("elements inside r :",ed)

    #degree list
    degree = np.sum(ed[:,1:M],axis=1)

    #print("degree :",degree)
    ed = np.array(ed)
    
    return dis_mat, s_m, ed, degree, s
distance(x,y)

[[ 0.   10.81 10.72 11.6  16.31  5.03 21.13  7.53 10.19 17.95]
 [10.81  0.   16.   13.79 14.31 10.46 14.43  4.2   3.33  8.84]
 [10.72 16.    0.    3.98  9.95  6.43 17.74 11.89 13.17 18.26]
 [11.6  13.79  3.98  0.    6.1   6.59 13.76 10.08 10.63 14.62]
 [16.31 14.31  9.95  6.1   0.   11.46  8.24 11.95 11.04 11.28]
 [ 5.03 10.46  6.43  6.59 11.46  0.   17.17  6.27  8.35 15.28]
 [21.13 14.43 17.74 13.76  8.24 17.17  0.   14.44 12.18  6.69]
 [ 7.53  4.2  11.89 10.08 11.95  6.27 14.44  0.    2.66 10.46]
 [10.19  3.33 13.17 10.63 11.04  8.35 12.18  2.66  0.    7.8 ]
 [17.95  8.84 18.26 14.62 11.28 15.28  6.69 10.46  7.8   0.  ]]


(array([[ 0.  ,  5.03,  7.53, 10.19, 10.72, 10.81, 11.6 , 16.31, 17.95,
         21.13],
        [ 0.  ,  3.33,  4.2 ,  8.84, 10.46, 10.81, 13.79, 14.31, 14.43,
         16.  ],
        [ 0.  ,  3.98,  6.43,  9.95, 10.72, 11.89, 13.17, 16.  , 17.74,
         18.26],
        [ 0.  ,  3.98,  6.1 ,  6.59, 10.08, 10.63, 11.6 , 13.76, 13.79,
         14.62],
        [ 0.  ,  6.1 ,  8.24,  9.95, 11.04, 11.28, 11.46, 11.95, 14.31,
         16.31],
        [ 0.  ,  5.03,  6.27,  6.43,  6.59,  8.35, 10.46, 11.46, 15.28,
         17.17],
        [ 0.  ,  6.69,  8.24, 12.18, 13.76, 14.43, 14.44, 17.17, 17.74,
         21.13],
        [ 0.  ,  2.66,  4.2 ,  6.27,  7.53, 10.08, 10.46, 11.89, 11.95,
         14.44],
        [ 0.  ,  2.66,  3.33,  7.8 ,  8.35, 10.19, 10.63, 11.04, 12.18,
         13.17],
        [ 0.  ,  6.69,  7.8 ,  8.84, 10.46, 11.28, 14.62, 15.28, 17.95,
         18.26]]),
 array([[ 0.  ,  5.03,  7.53, 10.19, 10.72, 10.81, 11.6 , 16.31, 17.95,
         21.13],
        [ 0.  ,  3.

In [7]:

def force(loc):
    
    N,L,r,M,eps,crep, cali, catt = param() #parameter call
    
    dis_mat, s_m, ed, degree, s = distance(loc[0],loc[1])
    
#    x, y, v, loc = position()
    #repulsion 


    R= [[],[]] #repulsion array

    for k in range(2):
        for i in range(N):
            suma = 0
            for j in range(degree[i]):
                pu = (loc[k][s[i][j]] - loc[k][i]) / ((s_m[i][s[i][j]])**2 + eps)
        #        print(pu, (s_m[i][s[i][j]])," " ,(i,j))
                suma = suma + pu
            suma = -crep*suma    
        #    print(suma, ", iteration : " , i, ", degree : ",degree[i])
            R[k].append(suma)
    R = np.array(R)
    #print(R)
    
    
    #alignment
    Al = [[],[]] #alignment array

    for k in range(2): # this loop is for assigning the values for both vx and vy
        for i in range(N):
            sumb = 0

            for j in range(degree[i]):
                ad = v[k][s[i][j]] - v[k][i]
                sumb = sumb + ad
            sumb = (cali/M)* sumb
            Al[k].append(sumb)
    print(Al)
    Al = np.array(Al)
    
    
    #attraction

    Att = [[],[]] # attraction array

    for k in range(2):
        for i in range(N):
            sumc = 0

            for j in range(degree[i]):
                ad2 = loc[k][s[i][j]] - loc[k][i]
                sumc = sumc + ad2
            sumc = (catt)* sumc
            Att[k].append(sumc)
    print(Att)
    Att = np.array(Att) 

    
    #defining bernoulli trail function

    pro = 0.5
    sk = [] # 1 and 0 matrix for L and F

    for i in range(N):         
        sk.append(np.random.choice((0,1),p=[1-pro,pro]))

    force_x = np.zeros(N)
    force_y = np.zeros(N)
    
    for k in range(N):
        if sk[k] == 1:
    #        print("leader :", k)
            force_x[k] = R[0][k-1]
            force_y[k] = (R[1][k-1])
        elif sk[k] == 0:
    #        print("follwer :", k)
            force_x[k] = R[0][k-1] + Al[0][k-1] + Att[0][k-1]
            force_y[k] = R[1][k-1] + Al[1][k-1] + Att[1][k-1]
    return [force_x,force_y] #it will return a list of Net_force with x and y components




In [8]:
z = [] #input
for k in range(N):
    z.append(loc[0][k]) # x in 0 to N-1
for k in range(N):
    z.append(loc[1][k]) # y in N to 2*N
for k in range(N):
    z.append(v[0][k]) # vx in 2N+1 to 3N
for k in range(N):
    z.append(v[1][k]) # vy in 3N+1 to 4N
z = np.array(z)   
print(z.ndim)

1


<ipython-input-8-054ae770c193>:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  z = np.array(z)


In [9]:
#model

def F(loc,v):
    
    dxdt = v[0]
    dydt = v[1]
    Ak = force(loc)
    vxdt = Ak[0]
    vydt = Ak[1]
    
    return [dxdt,dydt], loc, [vxdt, vydt]

#F(loc,v)

#print(type(z))
tt = np.linspace(0,50,10000)

In [10]:
g = lambda t : np.zeros(N)

In [11]:
def G():
    dxdt = [0 for x in range(N)]
    dydt = [0 for x in range(N)]
    vxdt = z[0:N]
    vydt = z[N+1 : 2*N]
    return [dxdt,dydt],[vxdt, vydt]#, dydt, vxdt,vydt

In [12]:
#G = [x,y,np.zeros([N,]),np.zeros([N,])]
'''
for k in range(N):
    G.append(x[k]) # x in 0 to N-1
for k in range(N):
    G.append(y[k]) # y in N to 2*N
for k in range(N):
    G.append(0) # vx in 2N+1 to 3N
for k in range(N):
    G.append(0) # vy in 3N+1 to 4N
G = np.array(G)   

#print(G)
#G= np.array(G).flatten()
#print(type(G))
#print(G)
# g = G(N)
'''


'\nfor k in range(N):\n    G.append(x[k]) # x in 0 to N-1\nfor k in range(N):\n    G.append(y[k]) # y in N to 2*N\nfor k in range(N):\n    G.append(0) # vx in 2N+1 to 3N\nfor k in range(N):\n    G.append(0) # vy in 3N+1 to 4N\nG = np.array(G)   \n\n#print(G)\n#G= np.array(G).flatten()\n#print(type(G))\n#print(G)\n# g = G(N)\n'

In [13]:
tt = linspace(0,50,10000)
#f=F(z,Nf)
yy = ddeint(F(loc,v),G(),tt)

[[ 0.   10.81 10.72 11.6  16.31  5.03 21.13  7.53 10.19 17.95]
 [10.81  0.   16.   13.79 14.31 10.46 14.43  4.2   3.33  8.84]
 [10.72 16.    0.    3.98  9.95  6.43 17.74 11.89 13.17 18.26]
 [11.6  13.79  3.98  0.    6.1   6.59 13.76 10.08 10.63 14.62]
 [16.31 14.31  9.95  6.1   0.   11.46  8.24 11.95 11.04 11.28]
 [ 5.03 10.46  6.43  6.59 11.46  0.   17.17  6.27  8.35 15.28]
 [21.13 14.43 17.74 13.76  8.24 17.17  0.   14.44 12.18  6.69]
 [ 7.53  4.2  11.89 10.08 11.95  6.27 14.44  0.    2.66 10.46]
 [10.19  3.33 13.17 10.63 11.04  8.35 12.18  2.66  0.    7.8 ]
 [17.95  8.84 18.26 14.62 11.28 15.28  6.69 10.46  7.8   0.  ]]
[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
[[array([-0.0422684]), array([-0.06368785]), array([0.06826238]), array([-0.01777614]), array([0.04227244]), array([0.08260565]), array([0.06515709]), array([0.02774514]), array([0.0359427]), array([-0.05014884])], [array([-0.02725407]), array([0.03140168]), array

TypeError: 'tuple' object is not callable

In [14]:
# REQUIRES Numpy and Scipy.

import scipy.integrate
import scipy.interpolate


class ddeVar:
    """
    The instances of this class are special function-like
    variables which store their past values in an interpolator and
    can be called for any past time: Y(t), Y(t-d).
    Very convenient for the integration of DDEs.
    """

    def __init__(self, g, tc=0):
        """ g(t) = expression of Y(t) for t<tc """

        self.g = g
        self.tc = tc
        # We must fill the interpolator with 2 points minimum

        self.interpolator = scipy.interpolate.interp1d(
            np.array([tc - 1, tc]),  # X
            np.array([self.g(tc), self.g(tc)]).T,  # Y
            kind="linear",
            bounds_error=False,
            fill_value=self.g(tc)
        )

    def update(self, t, Y):
        """ Add one new (ti,yi) to the interpolator """
        Y2 = Y if (Y.size == 1) else np.array([Y]).T
        self.interpolator = scipy.interpolate.interp1d(
            np.hstack([self.interpolator.x, [t]]),  # X
            np.hstack([self.interpolator.y, Y2]),  # Y
            kind="linear",
            bounds_error=False,
            fill_value=Y
        )

    def __call__(self, t=0):
        """ Y(t) will return the instance's value at time t """

        return self.g(t) if (t <= self.tc) else self.interpolator(t)


class dde(scipy.integrate.ode):
    """
    This class overwrites a few functions of ``scipy.integrate.ode``
    to allow for updates of the pseudo-variable Y between each
    integration step.
    """

    def __init__(self, f, jac=None):
        def f2(t, y, args):
            return f(self.Y, t, *args)

        scipy.integrate.ode.__init__(self, f2, jac)
        self.set_f_params(None)

    def integrate(self, t, step=0, relax=0):

        scipy.integrate.ode.integrate(self, t, step, relax)
        self.Y.update(self.t, self.y)
        return self.y

    def set_initial_value(self, Y):

        self.Y = Y  #!!! Y will be modified during integration
        scipy.integrate.ode.set_initial_value(self, Y(Y.tc), Y.tc)


def ddeint(func, g, tt, fargs=None):
    """ Solves Delay Differential Equations
    Similar to scipy.integrate.odeint. Solves a Delay differential
    Equation system (DDE) defined by
        Y(t) = g(t) for t<0
        Y'(t) = func(Y,t) for t>= 0
    Where func can involve past values of Y, like Y(t-d).
    
    Parameters
    -----------
    
    func
      a function Y,t,args -> Y'(t), where args is optional.
      The variable Y is an instance of class ddeVar, which means that
      it is called like a function: Y(t), Y(t-d), etc. Y(t) returns
      either a number or a numpy array (for multivariate systems).
    g
      The 'history function'. A function g(t)=Y(t) for t<0, g(t)
      returns either a number or a numpy array (for multivariate
      systems).
    
    tt
      The vector of times [t0, t1, ...] at which the system must
      be solved.
    fargs
      Additional arguments to be passed to parameter ``func``, if any.
    Examples
    ---------
    
    We will solve the delayed Lotka-Volterra system defined as
    
        For t < 0:
        x(t) = 1+t
        y(t) = 2-t
    
        For t >= 0:
        dx/dt =  0.5* ( 1- y(t-d) )
        dy/dt = -0.5* ( 1- x(t-d) )
    
    The delay ``d`` is a tunable parameter of the model.
    >>> import numpy as np
    >>> from ddeint import ddeint
    >>> 
    >>> def model(XY,t,d):
    >>>     x, y = XY(t)
    >>>     xd, yd = XY(t-d)
    >>>     return np.array([0.5*x*(1-yd), -0.5*y*(1-xd)])
    >>> 
    >>> g = lambda t : np.array([1+t,2-t]) # 'history' at t<0
    >>> tt = np.linspace(0,30,20000) # times for integration
    >>> d = 0.5 # set parameter d 
    >>> yy = ddeint(model,g,tt,fargs=(d,)) # solve the DDE !
     
    """

    dde_ = dde(func)
    dde_.set_initial_value(ddeVar(g, tt[0]))
    dde_.set_f_params(fargs if fargs else [])
    results = [dde_.integrate(dde_.t + dt) for dt in np.diff(tt)]
    return np.array([g(tt[0])] + results)

In [19]:
import numpy as np
from ddeint import ddeint
 
def model(XY,t,d):
    x, y = XY(t)
    xd, yd = XY(t-d)
    return np.array([0.5*x*(1-yd), -0.5*y*(1-xd)])

g = lambda t : np.array([1+t,2-t]) # 'history' at t<0
tt = np.linspace(0,30,20000) # times for integration
d = 0.5 # set parameter d 
yy = ddeint(model,g,tt,fargs=(d,)) # solve the DDE 
print(yy)

[[1.00000000e+00 2.00000000e+00]
 [9.98875573e-01 1.99925122e+00]
 [9.97752215e-01 1.99850456e+00]
 ...
 [2.03957546e-07 7.98715285e-03]
 [2.04108481e-07 7.98114314e-03]
 [2.04259517e-07 7.97513747e-03]]


In [18]:
print(yy)

[[1.00000000e+00 2.00000000e+00]
 [9.98875573e-01 1.99925122e+00]
 [9.97752215e-01 1.99850456e+00]
 ...
 [2.03957546e-07 7.98715285e-03]
 [2.04108481e-07 7.98114314e-03]
 [2.04259517e-07 7.97513747e-03]]


In [17]:
x12 

NameError: name 'x12' is not defined

In [ ]:
def complete():
    